Repository sveltejs/svelte, pull requests merged in 2021-11, with the labels that each got.

#6888 [docs] "What's new in Svelte" November newsletter
  site/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md
Labels: docs

#6893 [docs] use new export import for marked 4 in examples
  site/content/examples/05-bindings/04-textarea-inputs/App.svelte
  site/content/tutorial/06-bindings/05-textarea-inputs/app-a/App.svelte
  site/content/tutorial/06-bindings/05-textarea-inputs/app-b/App.svelte
Labels: docs

#6903 [docs] use on directives for link load
  site/content/examples/16-context/00-context-api/Map.svelte
  site/content/tutorial/15-context/01-context-api/app-a/Map.svelte
  site/content/tutorial/15-context/01-context-api/app-b/Map.svelte
Labels: docs

#6887 [docs] Document the effect of the order of bind: and on:
  site/content/docs/02-template-syntax.md
Labels: docs

#6905 [docs] clarify which routers have SSR support
  site/content/faq/900-is-there-a-router.md
Labels: docs

#6909 [refactor] refactor trim utils and write tests
  src/compiler/utils/patterns.ts
  src/compiler/utils/trim.ts
  test/utils/index.ts
Labels: perf, compiler

#6935 site: disable Vite vendor chunk
  site/package-lock.json
  site/package.json
  site/svelte.config.js
Labels: site

#6895 [docs] clarified definition of "local transition" in tutorial
  site/content/tutorial/10-transitions/07-local-transitions/text.md
Labels: docs

#6962 [docs] Use a simpler demo for the first actions tutorial (#5014)
  site/content/examples/13-actions/00-actions/App.svelte
  site/content/examples/13-actions/00-actions/click_outside.js
  site/content/examples/13-actions/03-actions-pannable/App.svelte
  site/content/examples/13-actions/03-actions-pannable/meta.json
  site/content/examples/13-actions/03-actions-pannable/pannable.js
  site/content/tutorial/12-actions/01-actions/app-a/App.svelte
  site/content/tutorial/12-actions/01-actions/app-a/click_outside.js
  site/content/tutorial/12-actions/01-actions/app-b/App.svelte
  site/content/tutorial/12-actions/01-actions/app-b/click_outside.js
  site/content/tutorial/12-actions/01-actions/app-b/pannable.js
  site/content/tutorial/12-actions/01-actions/text.md
  site/static/examples/thumbnails/actions-pannable.jpg
Labels: docs

#6815 [docs] A reference of the field variable is missing in the sidebar
  site/content/tutorial/06-bindings/14-component-this/text.md
Labels: docs
