Repository sveltejs/svelte, pull requests merged in 2021-03, with the labels that each got.

#6033 "What's new in Svelte" March newsletter
  site/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md
Labels: site: blog post

#6124 Update FAQ for SvelteKit beta
  site/content/faq/1200-how-do-i-do-hmr.md
  site/content/faq/900-is-there-a-router.md
Labels: site: docs

#6122 Export interfaces Spring and Tweened
  src/runtime/motion/spring.ts
  src/runtime/motion/tweened.ts
Labels: feature: typescript

#6056 Export the EasingFunction type
  src/runtime/transition/index.ts
Labels: feature: typescript

#5221 Export interfaces for transition params
  src/runtime/transition/index.ts
Labels: feature: typescript

#5887 Export store's useful typescript definitions - close #5864
  src/runtime/store/index.ts
Labels: feature: typescript

#6090 Tutorial: remove outline on scrollbar thumb
  site/src/routes/tutorial/[slug]/index.svelte
Labels: site: tutorial
