Repository sveltejs/svelte, pull requests merged in 2021-01, with the labels that each got.

#5822 Added aria roles for WAI-ARIA Graphics Module standard
  src/compiler/compile/nodes/Element.ts
Labels: feature: a11y

#5878 change detected language to TypeScript
  .gitattributes
Labels: meta

#5921 docs: define component before demonstrating usage
  site/content/docs/02-template-syntax.md
Labels: site: docs
